version: "3.7"

services:
  game:
    image: lynnfaraday/aresmush:latest
    working_dir: /ares
    volumes:
      - ${PWD}:/ares
    user: ares
    ports:
      - 4200:4200
      - 4201:4201
      - 4202:4202
      - 4203:4203
    tty: true
    command: redis-server /ares/data/redis.conf